# Generated by Django 4.0.5 on 2022-11-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('itemId', models.IntegerField(primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=100)),
                ('pid', models.IntegerField()),
            ],
            options={
                'db_table': 'itemsTable',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'productTable',
            },
        ),
    ]
